name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.2
    strategy:
      matrix:
        channel: [win, linux, mac, web] # Remove channel if not releasing (Available: win, linux, mac, web)
    env:
      GAME: suicide-hero # Change game name
      CHANNEL: ${{matrix.channel}}
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - run: sh scripts/prepare.sh
      - run: sh scripts/generate-build.sh
      - run: sh scripts/build.sh $CHANNEL $GAME
      - name: Publish Itch
        if: env.BUTLER_API_KEY && env.GAME && !contains(github.ref, '-pre')
        shell: bash
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}
          USER: ${{secrets.ITCHIO_USER}}
        run: butler push build/$CHANNEL kuma-gee/$GAME:$CHANNEL --userversion ${GITHUB_REF/refs\/tags\//}
      - run: sh scripts/package.sh $CHANNEL
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/**/*.zip
  github-release:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: ls
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            **/*.zip
      
