name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unit Test
        run: sh scripts/test.sh
        timeout-minutes: 5
